# 01 Data Preparation 
### What is done here: 
 - Raw Data from DBPedia is downloaded
 - Raw Data is preprocessed for ingestion in ElasticSearch
 - Connection is generated between DBPedia Id and Wikidata Id
### Data Source: https://downloads.dbpedia.org/2015-10/core/

In [4]:
import re
import requests
import bz2
import pandas as pd

In [5]:
def download_file(url, output_path):
    """Download a file from the specified URL to the output path."""
    response = requests.get(url, stream=True, verify=False)
    if response.status_code == 200:
        with open(output_path, 'wb') as file:
            for chunk in response.iter_content(chunk_size=1024):
                file.write(chunk)
        print(f"File downloaded: {output_path}")
    else:
        raise Exception(f"Failed to download file. HTTP Status Code: {response.status_code}")

def extract_bz2(file_path, output_path):
    """Extract a .bz2 file to the specified output path."""
    with bz2.BZ2File(file_path, 'rb') as bz2_file:
        with open(output_path, 'wb') as extracted_file:
            extracted_file.write(bz2_file.read())
        print(f"File extracted: {output_path}")

### Download and prepare the labels

In [15]:
url = "https://downloads.dbpedia.org/2015-10/core/labels_en.ttl.bz2" 
downloaded_file = "../03_data/raw_data/dbpedia/labels_en.ttl.bz2"
extracted_file = "../03_data/raw_data/dbpedia/labels_en.ttl"
download_file(url, downloaded_file)
extract_bz2(downloaded_file, extracted_file)

c:\Users\marvi\.conda\envs\masterthesis\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'downloads.dbpedia.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File downloaded: ../03_data/raw_data/labels_en.ttl.bz2
File extracted: ../03_data/raw_data/labels_en.ttl

In [ ]:
# Read labels File and attach it to a dictionary
labels = []
with open(extracted_file) as file:
    lines = file.readlines()
    for line in lines[1:-1]: # Start and End line contain the timestamp of dbpedia dump.
        labels.append({
            "id": line.split(" ")[0].replace("http://dbpedia.org/resource/","dbpedia:"),
            "title": line.split(">")[2].strip()[1:].replace('"@en .',""),
            "uri": line.split(" ")[0]
        })

In [ ]:

# liste = []
# with open("../raw_data/dbpedia/labels_en.ttl") as file:
#     lines = file.readlines()
#     for line in lines[1:-1]:
#         liste.append({
#             "id": line.split(" ")[0].replace("<http://dbpedia.org/resource/","dbpedia:")[:-1],
#             "title": line.split(">")[2].strip()[1:].replace('"@en .',""),
#             "uri": line.split(" ")[0]
#         })

### Download and prepare the short abstracts

In [21]:
url = "https://downloads.dbpedia.org/2015-10/core/short_abstracts_en.ttl.bz2" 
downloaded_file = "../03_data/raw_data/dbpedia/short_abstracts_en.ttl.bz2"
extracted_file = "../03_data/raw_data/dbpedia/short_abstracts_en.ttl"
download_file(url, downloaded_file)
extract_bz2(downloaded_file, extracted_file)

c:\Users\marvi\.conda\envs\masterthesis\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'downloads.dbpedia.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File downloaded: ../03_data/raw_data/short_abstracts_en.ttl.bz2
File extracted: ../03_data/raw_data/short_abstracts_en.ttl

In [ ]:
abstracts = []
with open(extracted_file) as file:
    lines = file.readlines()
    for line in lines[1:-1]: # Start and End line contain the timestamp of dbpedia dump.
        abstracts.append({
                "id": line.split(" ")[0].replace("http://dbpedia.org/resource/","dbpedia:"),
                "short_abstract": line.split(">")[2].strip()[1:].replace('"@en .',"")
            })

### Merge labels and abstracts to get a preprocessed DataFrame

In [28]:
# Create pandas DataFrames from labels and abstracts
labels = pd.DataFrame(labels)
abstracts = pd.DataFrame(abstracts)
# Remove empty abstract nodes
abstracts = abstracts[abstracts["short_abstract"]!=""]
# Merge labels and abstracts to get a complete DF for the Graph nodes.
# Inner Merge to keep only items that exist in both labels and abstracts
final_df = pd.merge(labels, abstracts,"inner", on="id")
final_df.to_parquet("../03_data/preprocessed_data/nodes_dbpedia.parquet")

### Create Wikidata - DBPedia Relation

In [29]:
url = "https://downloads.dbpedia.org/2015-10/core/page_ids_en.ttl.bz2" 
downloaded_file = "../03_data/raw_data/dbpedia/page_ids_en.ttl.bz2"
extracted_file = "../03_data/raw_data/dbpedia/page_ids_en.ttl"
download_file(url, downloaded_file)
extract_bz2(downloaded_file, extracted_file)

c:\Users\marvi\.conda\envs\masterthesis\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'downloads.dbpedia.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File downloaded: ../03_data/raw_data/page_ids_en.ttl.bz2
File extracted: ../03_data/raw_data/page_ids_en.ttl

In [5]:
mapping = []
with open(extracted_file) as file:
    lines = file.readlines()
    for line in lines[1:-1]:
        mapping.append({
                "id": line.split(" ")[0].replace("http://dbpedia.org/resource/","dbpedia:"),
                "page_id": int(re.search(r'"\d{1,8}"', line).group()[1:-1])
            })

In [6]:
pd.DataFrame(mapping).to_parquet('../03_data/preprocessed_data/mapping_dbpedia_wikidata.parquet')

In [6]:
url = "https://downloads.dbpedia.org/2016-10/core/page_ids_en.ttl.bz2" 
downloaded_file = "../03_data/raw_data/dbpedia/page_ids_en-2016.ttl.bz2"
extracted_file = "../03_data/raw_data/dbpedia/page_ids_en-2016.ttl"
download_file(url, downloaded_file)
extract_bz2(downloaded_file, extracted_file)

c:\Users\marvi\.conda\envs\masterthesis\Lib\site-packages\urllib3\connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'downloads.dbpedia.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

File downloaded: ../03_data/raw_data/dbpedia/page_ids_en-2016.ttl.bz2
File extracted: ../03_data/raw_data/dbpedia/page_ids_en-2016.ttl

In [7]:
mapping = []
with open(extracted_file) as file:
    lines = file.readlines()
    for line in lines[1:-1]:
        mapping.append({
                "id": line.split(" ")[0].replace("http://dbpedia.org/resource/","dbpedia:"),
                "page_id": int(re.search(r'"\d{1,8}"', line).group()[1:-1])
            })

In [8]:
pd.DataFrame(mapping).to_parquet('../03_data/preprocessed_data/mapping_dbpedia_wikidata-2016.parquet')

In [1]:
import pandas as pd

final_df = pd.read_parquet("nodes_dbpedia.parquet")

In [2]:
item_to_index = final_df["uri"].to_dict()
inv_item_to_index = {v: k for k, v in item_to_index.items()}
keys = inv_item_to_index.keys()

In [ ]:
from itertools import islice

In [4]:
rel_df = []
n = 1000000
with open("./page_links_en.ttl/page_links_en.ttl") as file:
    file.readline()
    for n_lines in iter(lambda: tuple(islice(file, n)), ()):
        for i, line in enumerate(n_lines):
            split_line = line.split(" ")
            if split_line[0] in keys and split_line[2] in keys:
                rel_df.append({
                    "left_node": inv_item_to_index[split_line[0]],
                    "right_node": inv_item_to_index[split_line[2]]
            })

In [5]:
len(rel_df)

2

In [5]:
pd.DataFrame(rel_df).to_parquet("rels.parquet")

In [ ]:
rel_df = []
for i, line in enumerate(lines[1:-1]):
    split_line = line.split(" ")
    if split_line[0] in keys and split_line[2] in keys:
        rel_df.append({
            "left_node": inv_item_to_index[split_line[0]],
            "right_node": inv_item_to_index[split_line[2]]
        })
    if i == 100:
        break

In [180]:
split_line = lines[75].split(" ")
len(final_df[final_df["uri"].isin([split_line[0],split_line[2]])])
final_df[final_df["uri"] == split_line[0]].index[0]
right_node = final_df[final_df["uri"] == split_line[2]].index[0]

In [174]:
lines[75]

'<http://dbpedia.org/resource/Albedo> <http://dbpedia.org/ontology/wikiPageWikiLink> <http://dbpedia.org/resource/Johann_Heinrich_Lambert> .\n'

In [184]:
inv_item_to_index

{'<http://dbpedia.org/resource/Albedo>': 0,
 '<http://dbpedia.org/resource/Anarchism>': 1,
 '<http://dbpedia.org/resource/Autism>': 2,
 '<http://dbpedia.org/resource/Achilles>': 3,
 '<http://dbpedia.org/resource/A>': 4,
 '<http://dbpedia.org/resource/Alabama>': 5,
 '<http://dbpedia.org/resource/An_American_in_Paris>': 6,
 '<http://dbpedia.org/resource/Actrius>': 7,
 '<http://dbpedia.org/resource/Animalia_(book)>': 8,
 '<http://dbpedia.org/resource/International_Atomic_Time>': 9,
 '<http://dbpedia.org/resource/Alain_Connes>': 10,
 '<http://dbpedia.org/resource/Allan_Dwan>': 11,
 '<http://dbpedia.org/resource/Academy_Awards>': 12,
 '<http://dbpedia.org/resource/List_of_Atlas_Shrugged_characters>': 13,
 '<http://dbpedia.org/resource/Astronomer>': 14,
 '<http://dbpedia.org/resource/Aristotle>': 15,
 '<http://dbpedia.org/resource/Altruism>': 16,
 '<http://dbpedia.org/resource/Academy_Award_for_Best_Production_Design>': 17,
 '<http://dbpedia.org/resource/ASCII>': 18,
 '<http://dbpedia.org/resource/Anthropology>': 19,
 '<http://dbpedia.org/resource/Algeria>': 20,
 '<http://dbpedia.org/resource/Alchemy>': 21,
 '<http://dbpedia.org/resource/Abacus>': 22,
 '<http://dbpedia.org/resource/Atomic_number>': 23,
 '<http://dbpedia.org/resource/Apollo_8>': 24,
 '<http://dbpedia.org/resource/Alkali_metal>': 25,
 '<http://dbpedia.org/resource/Analysis_of_variance>': 26,
 '<http://dbpedia.org/resource/Apollo_11>': 27,
 '<http://dbpedia.org/resource/Ayn_Rand>': 28,
 '<http://dbpedia.org/resource/Andre_Agassi>': 29,
 '<http://dbpedia.org/resource/Agriculture>': 30,
 '<http://dbpedia.org/resource/Apollo>': 31,
 '<http://dbpedia.org/resource/Aldous_Huxley>': 32,
 '<http://dbpedia.org/resource/Andorra>': 33,
 '<http://dbpedia.org/resource/Animal_Farm>': 34,
 '<http://dbpedia.org/resource/Alaska>': 35,
 '<http://dbpedia.org/resource/Amphibian>': 36,
 '<http://dbpedia.org/resource/Appellate_court>': 37,
 '<http://dbpedia.org/resource/Arraignment>': 38,
 '<http://dbpedia.org/resource/Answer>': 39,
 '<http://dbpedia.org/resource/Appellate_procedure_in_the_United_States>': 40,
 '<http://dbpedia.org/resource/Alkane>': 41,
 '<http://dbpedia.org/resource/America_the_Beautiful>': 42,
 '<http://dbpedia.org/resource/Acid>': 43,
 '<http://dbpedia.org/resource/American_National_Standards_Institute>': 44,
 '<http://dbpedia.org/resource/Astronaut>': 45,
 '<http://dbpedia.org/resource/Asphalt>': 46,
 '<http://dbpedia.org/resource/Assistive_technology>': 47,
 '<http://dbpedia.org/resource/Algae>': 48,
 '<http://dbpedia.org/resource/A_Modest_Proposal>': 49,
 '<http://dbpedia.org/resource/Afroasiatic_languages>': 50,
 '<http://dbpedia.org/resource/American_Football_Conference>': 51,
 '<http://dbpedia.org/resource/Austroasiatic_languages>': 52,
 '<http://dbpedia.org/resource/Arithmetic_mean>': 53,
 '<http://dbpedia.org/resource/Abraham_Lincoln>': 54,
 '<http://dbpedia.org/resource/Animation>': 55,
 '<http://dbpedia.org/resource/Atlantic_Ocean>': 56,
 '<http://dbpedia.org/resource/Articles_of_Confederation>': 57,
 '<http://dbpedia.org/resource/Aruba>': 58,
 '<http://dbpedia.org/resource/Aardwolf>': 59,
 '<http://dbpedia.org/resource/Adventure>': 60,
 '<http://dbpedia.org/resource/Asia>': 61,
 '<http://dbpedia.org/resource/Algorithms_(journal)>': 62,
 '<http://dbpedia.org/resource/Allah>': 63,
 '<http://dbpedia.org/resource/Actinopterygii>': 64,
 '<http://dbpedia.org/resource/Angola>': 65,
 '<http://dbpedia.org/resource/Arthur_Schopenhauer>': 66,
 '<http://dbpedia.org/resource/Economy_of_Angola>': 67,
 '<http://dbpedia.org/resource/Android_(robot)>': 68,
 '<http://dbpedia.org/resource/Angolan_Armed_Forces>': 69,
 '<http://dbpedia.org/resource/Foreign_relations_of_Angola>': 70,
 '<http://dbpedia.org/resource/Transport_in_Angola>': 71,
 '<http://dbpedia.org/resource/Politics_of_Angola>': 72,
 '<http://dbpedia.org/resource/Demographics_of_Angola>': 73,
 '<http://dbpedia.org/resource/Ambiguity>': 74,
 '<http://dbpedia.org/resource/Anatomy>': 75,
 '<http://dbpedia.org/resource/Andrei_Tarkovsky>': 76,
 '<http://dbpedia.org/resource/Alphabet>': 77,
 '<http://dbpedia.org/resource/Aardvark>': 78,
 '<http://dbpedia.org/resource/Adobe>': 79,
 '<http://dbpedia.org/resource/Alberta>': 80,
 '<http://dbpedia.org/resource/American_Revolutionary_War>': 81,
 '<http://dbpedia.org/resource/Alfred_Hitchcock>': 82,
 '<http://dbpedia.org/resource/Asteroid>': 83,
 '<http://dbpedia.org/resource/Azerbaijan>': 84,
 '<http://dbpedia.org/resource/Alfred_Korzybski>': 85,
 '<http://dbpedia.org/resource/Asterales>': 86,
 '<http://dbpedia.org/resource/Affidavit>': 87,
 '<http://dbpedia.org/resource/Allocution>': 88,
 '<http://dbpedia.org/resource/Asteroids_(video_game)>': 89,
 '<http://dbpedia.org/resource/Anime>': 90,
 '<http://dbpedia.org/resource/Mouthwash>': 91,
 '<http://dbpedia.org/resource/Alismatales>': 92,
 '<http://dbpedia.org/resource/Apiales>': 93,
 '<http://dbpedia.org/resource/Ampere>': 94,
 '<http://dbpedia.org/resource/Annual_plant>': 95,
 '<http://dbpedia.org/resource/Abortion>': 96,
 '<http://dbpedia.org/resource/Anthophyta>': 97,
 '<http://dbpedia.org/resource/Aikido>': 98,
 '<http://dbpedia.org/resource/Agnostida>': 99,
 '<http://dbpedia.org/resource/Abstract_(law)>': 100,
 '<http://dbpedia.org/resource/Art>': 101,
 '<http://dbpedia.org/resource/Albert_Sidney_Johnston>': 102,
 '<http://dbpedia.org/resource/Afghanistan>': 103,
 '<http://dbpedia.org/resource/Albania>': 104,
 '<http://dbpedia.org/resource/Albert_Einstein>': 105,
 '<http://dbpedia.org/resource/Amateur_astronomy>': 106,
 '<http://dbpedia.org/resource/Arabic>': 107,
 '<http://dbpedia.org/resource/Algorithm>': 108,
 '<http://dbpedia.org/resource/Ankara>': 109,
 '<http://dbpedia.org/resource/Aquarius_(constellation)>': 110,
 '<http://dbpedia.org/resource/American_Civil_War>': 111,
 '<http://dbpedia.org/resource/Amsterdam>': 112,
 '<http://dbpedia.org/resource/Apple_Inc.>': 113,
 '<http://dbpedia.org/resource/Alexander_Graham_Bell>': 114,
 '<http://dbpedia.org/resource/Audi>': 115,
 '<http://dbpedia.org/resource/Attila>': 116,
 '<http://dbpedia.org/resource/Anatolia>': 117,
 '<http://dbpedia.org/resource/Aberdeenshire>': 118,
 '<http://dbpedia.org/resource/Aztlan_Underground>': 119,
 '<http://dbpedia.org/resource/A_Clockwork_Orange>': 120,
 '<http://dbpedia.org/resource/Altaic_languages>': 121,
 '<http://dbpedia.org/resource/Alfred_Nobel>': 122,
 '<http://dbpedia.org/resource/Aegean_Sea>': 123,
 '<http://dbpedia.org/resource/Asparagales>': 124,
 '<http://dbpedia.org/resource/Alexander_the_Great>': 125,
 '<http://dbpedia.org/resource/Anaconda>': 126,
 '<http://dbpedia.org/resource/Austrian_German>': 127,
 '<http://dbpedia.org/resource/Museum_of_Work>': 128,
 '<http://dbpedia.org/resource/Aircraft>': 129,
 '<http://dbpedia.org/resource/Aries_(constellation)>': 130,
 '<http://dbpedia.org/resource/Ancient_Egypt>': 131,
 '<http://dbpedia.org/resource/Akira_Kurosawa>': 132,
 '<http://dbpedia.org/resource/Arsenic>': 133,
 '<http://dbpedia.org/resource/Americium>': 134,
 '<http://dbpedia.org/resource/Antimony>': 135,
 '<http://dbpedia.org/resource/Actinium>': 136,
 '<http://dbpedia.org/resource/Argon>': 137,
 '<http://dbpedia.org/resource/Anna_Kournikova>': 138,
 '<http://dbpedia.org/resource/Agnosticism>': 139,
 '<http://dbpedia.org/resource/ABBA>': 140,
 '<http://dbpedia.org/resource/MessagePad>': 141,
 '<http://dbpedia.org/resource/Alfons_Maria_Jakob>': 142,
 '<http://dbpedia.org/resource/A._E._van_Vogt>': 143,
 '<http://dbpedia.org/resource/Abugida>': 144,
 '<http://dbpedia.org/resource/Analog_Brothers>': 145,
 '<http://dbpedia.org/resource/Allegiance>': 146,
 '<http://dbpedia.org/resource/Motor_neuron_disease>': 147,
 '<http://dbpedia.org/resource/Abjad>': 148,
 '<http://dbpedia.org/resource/Andy_Warhol>': 149,
 '<http://dbpedia.org/resource/Alp_Arslan>': 150,
 '<http://dbpedia.org/resource/American_Film_Institute>': 151,
 '<http://dbpedia.org/resource/Arable_land>': 152,
 '<http://dbpedia.org/resource/Advanced_Chemistry>': 153,
 '<http://dbpedia.org/resource/Aluminium>': 154,
 '<http://dbpedia.org/resource/Arne_Kaijser>': 155,
 '<http://dbpedia.org/resource/Archipelago>': 156,
 '<http://dbpedia.org/resource/Anglican_Communion>': 157,
 '<http://dbpedia.org/resource/Astatine>': 158,
 '<http://dbpedia.org/resource/Atom>': 159,
 '<http://dbpedia.org/resource/Author>': 160,
 '<http://dbpedia.org/resource/Angst>': 161,
 '<http://dbpedia.org/resource/Axiom>': 162,
 '<http://dbpedia.org/resource/Andrey_Markov>': 163,
 '<http://dbpedia.org/resource/Anxiety>': 164,
 '<http://dbpedia.org/resource/Asociación_Alumni>': 165,
 '<http://dbpedia.org/resource/Alpha>': 166,
 '<http://dbpedia.org/resource/Alvin_Toffler>': 167,
 '<http://dbpedia.org/resource/A._A._Milne>': 168,
 '<http://dbpedia.org/resource/The_Amazing_Spider-Man>': 169,
 '<http://dbpedia.org/resource/August_Derleth>': 170,
 '<http://dbpedia.org/resource/Miss_Marple>': 171,
 '<http://dbpedia.org/resource/Hercule_Poirot>': 172,
 '<http://dbpedia.org/resource/April>': 173,
 '<http://dbpedia.org/resource/Agatha_Christie>': 174,
 '<http://dbpedia.org/resource/Albert_Speer>': 175,
 '<http://dbpedia.org/resource/Ada_Lovelace>': 176,
 '<http://dbpedia.org/resource/Axon>': 177,
 '<http://dbpedia.org/resource/American_shot>': 178,
 '<http://dbpedia.org/resource/Acute_disseminated_encephalomyelitis>': 179,
 '<http://dbpedia.org/resource/Azincourt>': 180,
 '<http://dbpedia.org/resource/Aramaic_alphabet>': 181,
 '<http://dbpedia.org/resource/Ataxia>': 182,
 '<http://dbpedia.org/resource/Apiaceae>': 183,
 '<http://dbpedia.org/resource/Asteraceae>': 184,
 '<http://dbpedia.org/resource/Abdul_Alhazred>': 185,
 '<http://dbpedia.org/resource/Applied_ethics>': 186,
 '<http://dbpedia.org/resource/Analog_signal>': 187,
 '<http://dbpedia.org/resource/Antigua_and_Barbuda>': 188,
 '<http://dbpedia.org/resource/Absolute_value>': 189,
 '<http://dbpedia.org/resource/Albert_Camus>': 190,
 '<http://dbpedia.org/resource/Alps>': 191,
 '<http://dbpedia.org/resource/The_Plague>': 192,
 '<http://dbpedia.org/resource/August>': 193,
 '<http://dbpedia.org/resource/Alcohol>': 194,
 '<http://dbpedia.org/resource/April_12>': 195,
 '<http://dbpedia.org/resource/April_30>': 196,
 '<http://dbpedia.org/resource/Algebraically_closed_field>': 197,
 '<http://dbpedia.org/resource/Aspect_ratio>': 198,
 '<http://dbpedia.org/resource/April_15>': 199,
 '<http://dbpedia.org/resource/April_6>': 200,
 '<http://dbpedia.org/resource/André_Gide>': 201,
 "<http://dbpedia.org/resource/All_Souls'_Day>": 202,
 '<http://dbpedia.org/resource/Aarhus>': 203,
 '<http://dbpedia.org/resource/Anarcho-capitalism>': 204,
 '<http://dbpedia.org/resource/August_27>': 205,
 '<http://dbpedia.org/resource/Auto_racing>': 206,
 '<http://dbpedia.org/resource/August_6>': 207,
 '<http://dbpedia.org/resource/August_9>': 208,
 '<http://dbpedia.org/resource/Aaron>': 209,
 '<http://dbpedia.org/resource/Aristophanes>': 210,
 '<http://dbpedia.org/resource/Anatoly_Karpov>': 211,
 '<http://dbpedia.org/resource/Allen_Ginsberg>': 212,
 '<http://dbpedia.org/resource/Austrian_School>': 213,
 '<http://dbpedia.org/resource/Abscess>': 214,
 '<http://dbpedia.org/resource/Albert_Schweitzer>': 215,
 '<http://dbpedia.org/resource/Amateur>': 216,
 '<http://dbpedia.org/resource/Northern_cavefish>': 217,
 '<http://dbpedia.org/resource/Anatole_France>': 218,
 '<http://dbpedia.org/resource/Alexis_Carrel>': 219,
 '<http://dbpedia.org/resource/Aalborg_Municipality>': 220,
 '<http://dbpedia.org/resource/August_22>': 221,
 '<http://dbpedia.org/resource/Geography_of_American_Samoa>': 222,
 '<http://dbpedia.org/resource/Demographics_of_American_Samoa>': 223,
 '<http://dbpedia.org/resource/Politics_of_American_Samoa>': 224,
 '<http://dbpedia.org/resource/Economy_of_Azerbaijan>': 225,
 '<http://dbpedia.org/resource/Achill_Island>': 226,
 '<http://dbpedia.org/resource/Demographics_of_Armenia>': 227,
 '<http://dbpedia.org/resource/Foreign_relations_of_Azerbaijan>': 228,
 '<http://dbpedia.org/resource/Azerbaijani_Armed_Forces>': 229,
 '<http://dbpedia.org/resource/Almond>': 230,
 '<http://dbpedia.org/resource/Telecommunications_in_Antigua_and_Barbuda>': 231,
 "<http://dbpedia.org/resource/America's_National_Game>": 232,
 '<http://dbpedia.org/resource/Royal_Antigua_and_Barbuda_Defence_Force>': 233,
 '<http://dbpedia.org/resource/Geography_of_Armenia>': 234,
 '<http://dbpedia.org/resource/Geography_of_Azerbaijan>': 235,
 '<http://dbpedia.org/resource/Transport_in_Armenia>': 236,
 '<http://dbpedia.org/resource/Politics_of_Armenia>': 237,
 '<http://dbpedia.org/resource/Economy_of_Armenia>': 238,
 '<http://dbpedia.org/resource/Transportation_in_American_Samoa>': 239,
 '<http://dbpedia.org/resource/Algorithms_for_calculating_variance>': 240,
 '<http://dbpedia.org/resource/Demographics_of_Antigua_and_Barbuda>': 241,
 '<http://dbpedia.org/resource/Politics_of_Antigua_and_Barbuda>': 242,
 '<http://dbpedia.org/resource/Armed_Forces_of_Armenia>': 243,
 '<http://dbpedia.org/resource/Foreign_relations_of_Armenia>': 244,
 '<http://dbpedia.org/resource/Augustin-Jean_Fresnel>': 245,
 '<http://dbpedia.org/resource/Economy_of_American_Samoa>': 246,
 '<http://dbpedia.org/resource/Amplitude_modulation>': 247,
 '<http://dbpedia.org/resource/Analysis>': 248,
 '<http://dbpedia.org/resource/August_13>': 249,
 '<http://dbpedia.org/resource/Architect>': 250,
 '<http://dbpedia.org/resource/Ancient_philosophy>': 251,
 '<http://dbpedia.org/resource/Afro_Celt_Sound_System>': 252,
 '<http://dbpedia.org/resource/Abbreviation>': 253,
 '<http://dbpedia.org/resource/Algebraic_number>': 254,
 '<http://dbpedia.org/resource/Ardipithecus>': 255,
 '<http://dbpedia.org/resource/Automorphism>': 256,
 '<http://dbpedia.org/resource/Abbot>': 257,
 '<http://dbpedia.org/resource/Avicenna>': 258,
 '<http://dbpedia.org/resource/Abner_Doubleday>': 259,
 '<http://dbpedia.org/resource/The_Ashes>': 260,
 '<http://dbpedia.org/resource/Antisemitism>': 261,
 '<http://dbpedia.org/resource/August_2>': 262,
 '<http://dbpedia.org/resource/Athena>': 263,
 '<http://dbpedia.org/resource/Angle>': 264,
 '<http://dbpedia.org/resource/Acoustics>': 265,
 '<http://dbpedia.org/resource/Astrometry>': 266,
 '<http://dbpedia.org/resource/Agrarianism>': 267,
 '<http://dbpedia.org/resource/Afterlife>': 268,
 '<http://dbpedia.org/resource/Amber_Diceless_Roleplaying_Game>': 269,
 '<http://dbpedia.org/resource/Artistic_revolution>': 270,
 '<http://dbpedia.org/resource/Alloy>': 271,
 '<http://dbpedia.org/resource/Artificial_intelligence>': 272,
 '<http://dbpedia.org/resource/Alan_Garner>': 273,
 '<http://dbpedia.org/resource/Anaximander>': 274,
 '<http://dbpedia.org/resource/April_1>': 275,
 '<http://dbpedia.org/resource/Adelaide>': 276,
 '<http://dbpedia.org/resource/Aleister_Crowley>': 277,
 '<http://dbpedia.org/resource/Ashmore_and_Cartier_Islands>': 278,
 '<http://dbpedia.org/resource/Atomic_orbital>': 279,
 '<http://dbpedia.org/resource/Astronomical_unit>': 280,
 '<http://dbpedia.org/resource/Telecommunications_in_Anguilla>': 281,
 '<http://dbpedia.org/resource/Area>': 282,
 '<http://dbpedia.org/resource/Artist>': 283,
 '<http://dbpedia.org/resource/Actaeon>': 284,
 '<http://dbpedia.org/resource/Alternate_history>': 285,
 '<http://dbpedia.org/resource/Applet>': 286,
 '<http://dbpedia.org/resource/Aphrodite>': 287,
 '<http://dbpedia.org/resource/Assembly_line>': 288,
 '<http://dbpedia.org/resource/Accordion>': 289,
 '<http://dbpedia.org/resource/Anglicanism>': 290,
 '<http://dbpedia.org/resource/Arianism>': 291,
 '<http://dbpedia.org/resource/August_3>': 292,
 '<http://dbpedia.org/resource/Analytical_Engine>': 293,
 '<http://dbpedia.org/resource/Antoninus_Pius>': 294,
 '<http://dbpedia.org/resource/Geography_of_Antarctica>': 295,
 '<http://dbpedia.org/resource/April_26>': 296,
 '<http://dbpedia.org/resource/Alexander_Mackenzie>': 297,
 '<http://dbpedia.org/resource/Transport_in_Antarctica>': 298,
 '<http://dbpedia.org/resource/August_1>': 299,
 '<http://dbpedia.org/resource/Extreme_poverty>': 300,
 '<http://dbpedia.org/resource/Advanced_Encryption_Standard>': 301,
 '<http://dbpedia.org/resource/Alfonso_Cuarón>': 302,
 '<http://dbpedia.org/resource/Ashoka>': 303,
 '<http://dbpedia.org/resource/Anisotropy>': 304,
 '<http://dbpedia.org/resource/Argot>': 305,
 '<http://dbpedia.org/resource/American_(word)>': 306,
 '<http://dbpedia.org/resource/Ada_(programming_language)>': 307,
 '<http://dbpedia.org/resource/Alan_Turing>': 308,
 '<http://dbpedia.org/resource/Athens>': 309,
 '<http://dbpedia.org/resource/Amino_acid>': 310,
 '<http://dbpedia.org/resource/Anguilla>': 311,
 '<http://dbpedia.org/resource/American_Sign_Language>': 312,
 '<http://dbpedia.org/resource/Augustus>': 313,
 '<http://dbpedia.org/resource/Arminianism>': 314,
 '<http://dbpedia.org/resource/Ames,_Iowa>': 315,
 '<http://dbpedia.org/resource/Antimatter>': 316,
 '<http://dbpedia.org/resource/Annales_School>': 317,
 '<http://dbpedia.org/resource/Abbey>': 318,
 '<http://dbpedia.org/resource/List_of_Governors_of_Alabama>': 319,
 '<http://dbpedia.org/resource/The_Alan_Parsons_Project>': 320,
 '<http://dbpedia.org/resource/Aromatic_hydrocarbon>': 321,
 '<http://dbpedia.org/resource/Almost_all>': 322,
 '<http://dbpedia.org/resource/Abbess>': 323,
 '<http://dbpedia.org/resource/Abensberg>': 324,
 '<http://dbpedia.org/resource/Alfred_Lawson>': 325,
 '<http://dbpedia.org/resource/Antarctic_Treaty_System>': 326,
 '<http://dbpedia.org/resource/Abdominal_surgery>': 327,
 '<http://dbpedia.org/resource/Apocrypha>': 328,
 '<http://dbpedia.org/resource/Geography_of_Alabama>': 329,
 '<http://dbpedia.org/resource/Abalone>': 330,
 '<http://dbpedia.org/resource/Park_Güell>': 331,
 '<http://dbpedia.org/resource/Casa_Batlló>': 332,
 '<http://dbpedia.org/resource/Antiparticle>': 333,
 '<http://dbpedia.org/resource/Casa_Milà>': 334,
 '<http://dbpedia.org/resource/Arabian_Prince>': 335,
 '<http://dbpedia.org/resource/Apache_Software_Foundation>': 336,
 '<http://dbpedia.org/resource/August_7>': 337,
 '<http://dbpedia.org/resource/August_8>': 338,
 '<http://dbpedia.org/resource/April_16>': 339,
 '<http://dbpedia.org/resource/Americans_with_Disabilities_Act_of_1990>': 340,
 '<http://dbpedia.org/resource/Apple_I>': 341,
 '<http://dbpedia.org/resource/Ancylopoda>': 342,
 '<http://dbpedia.org/resource/Atanasoff–Berry_computer>': 343,
 '<http://dbpedia.org/resource/Anchor>': 344,
 '<http://dbpedia.org/resource/Apatosaurus>': 345,
 '<http://dbpedia.org/resource/Anagram>': 346,
 '<http://dbpedia.org/resource/Anbar_(town)>': 347,
 '<http://dbpedia.org/resource/Allosaurus>': 348,
 '<http://dbpedia.org/resource/Anazarbus>': 349,
 '<http://dbpedia.org/resource/Andes>': 350,
 '<http://dbpedia.org/resource/Aare>': 351,
 '<http://dbpedia.org/resource/Antonio_Vivaldi>': 352,
 '<http://dbpedia.org/resource/Animism>': 353,
 '<http://dbpedia.org/resource/Amide>': 354,
 '<http://dbpedia.org/resource/Amos_Bronson_Alcott>': 355,
 '<http://dbpedia.org/resource/Algol>': 356,
 '<http://dbpedia.org/resource/August_14>': 357,
 '<http://dbpedia.org/resource/Angilbert>': 358,
 '<http://dbpedia.org/resource/AOL>': 359,
 '<http://dbpedia.org/resource/Alcuin>': 360,
 '<http://dbpedia.org/resource/Ahab>': 361,
 '<http://dbpedia.org/resource/Alder>': 362,
 '<http://dbpedia.org/resource/Dasyproctidae>': 363,
 '<http://dbpedia.org/resource/Alligatoridae>': 364,
 '<http://dbpedia.org/resource/Alphorn>': 365,
 '<http://dbpedia.org/resource/Amber>': 366,
 '<http://dbpedia.org/resource/Amalaric>': 367,
 '<http://dbpedia.org/resource/Ambracia>': 368,
 '<http://dbpedia.org/resource/April_29>': 369,
 '<http://dbpedia.org/resource/Amazing_Grace>': 370,
 '<http://dbpedia.org/resource/Ambrose>': 371,
 '<http://dbpedia.org/resource/Absolute_zero>': 372,
 '<http://dbpedia.org/resource/Anno_Domini>': 373,
 '<http://dbpedia.org/resource/Amine>': 374,
 '<http://dbpedia.org/resource/Alabaster>': 375,
 '<http://dbpedia.org/resource/Arachnophobia>': 376,
 '<http://dbpedia.org/resource/Army>': 377,
 '<http://dbpedia.org/resource/Anadyr_River>': 378,

In [169]:
rel_df

[{'left_node': 0, 'right_node': 7819},
 {'left_node': 0, 'right_node': 230908},
 {'left_node': 0, 'right_node': 23905},
 {'left_node': 0, 'right_node': 4628},
 {'left_node': 0, 'right_node': 7937},
 {'left_node': 0, 'right_node': 254811},
 {'left_node': 0, 'right_node': 78332},
 {'left_node': 0, 'right_node': 23598},
 {'left_node': 0, 'right_node': 19785},
 {'left_node': 0, 'right_node': 790400},
 {'left_node': 0, 'right_node': 40199},
 {'left_node': 0, 'right_node': 3834167},
 {'left_node': 0, 'right_node': 30245},
 {'left_node': 0, 'right_node': 21083},
 {'left_node': 0, 'right_node': 3863},
 {'left_node': 0, 'right_node': 883263},
 {'left_node': 0, 'right_node': 2146941},
 {'left_node': 0, 'right_node': 178352},
 {'left_node': 0, 'right_node': 178304},
 {'left_node': 0, 'right_node': 258328},
 {'left_node': 0, 'right_node': 9185},
 {'left_node': 0, 'right_node': 989171},
 {'left_node': 0, 'right_node': 5358},
 {'left_node': 0, 'right_node': 303071},
 {'left_node': 0, 'right_node': 989174},
 {'left_node': 0, 'right_node': 10297},
 {'left_node': 0, 'right_node': 24821},
 {'left_node': 0, 'right_node': 83},
 {'left_node': 0, 'right_node': 102438},
 {'left_node': 0, 'right_node': 12175},
 {'left_node': 0, 'right_node': 101561},
 {'left_node': 0, 'right_node': 102736},
 {'left_node': 0, 'right_node': 1100030},
 {'left_node': 0, 'right_node': 22333},
 {'left_node': 0, 'right_node': 787773},
 {'left_node': 0, 'right_node': 890507}]

In [166]:
final_df.iloc[890507]

id                                         dbpedia:Space_weathering
title                                              Space weathering
uri                  <http://dbpedia.org/resource/Space_weathering>
short_abstract    Space weathering is the damage that occurs to ...
Name: 890507, dtype: object

In [163]:
right_node

890507

In [152]:
len(final_df[final_df["uri"].isin([split_line[0],split_line[2]])])

1

In [156]:
final_df[final_df["uri"]==split_line[0]]

Empty DataFrame
Columns: [id, title, uri, short_abstract]
Index: []

In [158]:
abstracts[abstracts["id"]=="dbpedia:AccessibleComputing"]

Empty DataFrame
Columns: [id, short_abstract]
Index: []

# Wikilinks

In [20]:
rel_df = []
n = 1000000
with open("./page_ids_en.ttl/page_ids_en.ttl") as file:
    for i in range(1000):
        print(file.readline())
        line = file.readline()

# started 2017-03-14T08:38:43Z

<http://dbpedia.org/resource/AfghanistanHistory> <http://dbpedia.org/ontology/wikiPageID> "13"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AfghanistanPeople> <http://dbpedia.org/ontology/wikiPageID> "15"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AfghanistanTransportations> <http://dbpedia.org/ontology/wikiPageID> "19"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AfghanistanTransnationalIssues> <http://dbpedia.org/ontology/wikiPageID> "21"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AmoeboidTaxa> <http://dbpedia.org/ontology/wikiPageID> "24"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AlbaniaHistory> <http://dbpedia.org/ontology/wikiPageID> "27"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AlbaniaEconomy> <http://dbpedia.org/ontology/wikiPageID> "36"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AbacuS> <http://dbpedia.org/ontology/wikiPageID> "46"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AfroAsiaticLanguages> <http://dbpedia.org/ontology/wikiPageID> "40"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AbbadideS> <http://dbpedia.org/ontology/wikiPageID> "48"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AbbevilleFrance> <http://dbpedia.org/ontology/wikiPageID> "50"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AbboT> <http://dbpedia.org/ontology/wikiPageID> "52"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Abbreviations> <http://dbpedia.org/ontology/wikiPageID> "53"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AtlasShruggedCompanies> <http://dbpedia.org/ontology/wikiPageID> "59"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AyersMusicPublishingCompany> <http://dbpedia.org/ontology/wikiPageID> "60"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AdolfHitler> <http://dbpedia.org/ontology/wikiPageID> "242"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AbeL> <http://dbpedia.org/ontology/wikiPageID> "248"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AbensbergGermany> <http://dbpedia.org/ontology/wikiPageID> "249"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ArthurKoestler> <http://dbpedia.org/ontology/wikiPageID> "254"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AsciiArt> <http://dbpedia.org/ontology/wikiPageID> "264"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AnchorageAlaska> <http://dbpedia.org/ontology/wikiPageID> "258"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ArgumentForms> <http://dbpedia.org/ontology/wikiPageID> "259"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AustriaLanguage> <http://dbpedia.org/ontology/wikiPageID> "271"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AcademicElitism> <http://dbpedia.org/ontology/wikiPageID> "272"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AmericanFootball> <http://dbpedia.org/ontology/wikiPageID> "276"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AndorrA> <http://dbpedia.org/ontology/wikiPageID> "280"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ActresseS> <http://dbpedia.org/ontology/wikiPageID> "289"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ActressesS> <http://dbpedia.org/ontology/wikiPageID> "296"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AustroAsiaticLanguages> <http://dbpedia.org/ontology/wikiPageID> "287"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ActionFilm> <http://dbpedia.org/ontology/wikiPageID> "302"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AppliedStatistics> <http://dbpedia.org/ontology/wikiPageID> "306"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Achilles> <http://dbpedia.org/ontology/wikiPageID> "305"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AutoRacing> <http://dbpedia.org/ontology/wikiPageID> "338"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Algeria/Transnational_Issues> <http://dbpedia.org/ontology/wikiPageID> "353"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Actrius> <http://dbpedia.org/ontology/wikiPageID> "330"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/International_Atomic_Time> <http://dbpedia.org/ontology/wikiPageID> "334"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Ameboid_stage> <http://dbpedia.org/ontology/wikiPageID> "583"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alien> <http://dbpedia.org/ontology/wikiPageID> "579"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alain_Connes> <http://dbpedia.org/ontology/wikiPageID> "340"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Albedo> <http://dbpedia.org/ontology/wikiPageID> "39"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Academy_Award_for_Best_Production_Design> <http://dbpedia.org/ontology/wikiPageID> "316"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Ashmore_And_Cartier_Islands> <http://dbpedia.org/ontology/wikiPageID> "589"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Artificial_languages> <http://dbpedia.org/ontology/wikiPageID> "596"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Andorra/Transnational_issues> <http://dbpedia.org/ontology/wikiPageID> "609"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AnEnquiryConcerningHumanUnderstanding> <http://dbpedia.org/ontology/wikiPageID> "618"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Arithmetic_mean> <http://dbpedia.org/ontology/wikiPageID> "612"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Austroasiatic_languages> <http://dbpedia.org/ontology/wikiPageID> "597"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aristotle> <http://dbpedia.org/ontology/wikiPageID> "308"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alchemy> <http://dbpedia.org/ontology/wikiPageID> "573"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Anthropology> <http://dbpedia.org/ontology/wikiPageID> "569"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Ada> <http://dbpedia.org/ontology/wikiPageID> "630"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ANOVA> <http://dbpedia.org/ontology/wikiPageID> "635"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Actress> <http://dbpedia.org/ontology/wikiPageID> "648"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Answer> <http://dbpedia.org/ontology/wikiPageID> "642"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Arraignment> <http://dbpedia.org/ontology/wikiPageID> "649"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Argument_(disambiguation)> <http://dbpedia.org/ontology/wikiPageID> "661"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Anarchism> <http://dbpedia.org/ontology/wikiPageID> "12"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aruba> <http://dbpedia.org/ontology/wikiPageID> "690"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Andrei_Tarkovsky> <http://dbpedia.org/ontology/wikiPageID> "676"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aardvark> <http://dbpedia.org/ontology/wikiPageID> "680"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aardwolf> <http://dbpedia.org/ontology/wikiPageID> "681"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Asphalt> <http://dbpedia.org/ontology/wikiPageID> "657"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alaska> <http://dbpedia.org/ontology/wikiPageID> "624"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Abraham_Lincoln> <http://dbpedia.org/ontology/wikiPageID> "307"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Ambiguity> <http://dbpedia.org/ontology/wikiPageID> "677"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Analysis_of_Variance> <http://dbpedia.org/ontology/wikiPageID> "687"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Algeria> <http://dbpedia.org/ontology/wikiPageID> "358"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Affirming_the_consequent> <http://dbpedia.org/ontology/wikiPageID> "675"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alabama> <http://dbpedia.org/ontology/wikiPageID> "303"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ASCII> <http://dbpedia.org/ontology/wikiPageID> "586"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Argument_form> <http://dbpedia.org/ontology/wikiPageID> "668"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alkane> <http://dbpedia.org/ontology/wikiPageID> "639"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/A_Modest_Proposal> <http://dbpedia.org/ontology/wikiPageID> "665"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Andorra> <http://dbpedia.org/ontology/wikiPageID> "600"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Acid> <http://dbpedia.org/ontology/wikiPageID> "656"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/American_National_Standards_Institute> <http://dbpedia.org/ontology/wikiPageID> "659"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Astronomy/History> <http://dbpedia.org/ontology/wikiPageID> "727"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Angola> <http://dbpedia.org/ontology/wikiPageID> "701"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Articles_of_Confederation> <http://dbpedia.org/ontology/wikiPageID> "691"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Economy_of_Angola> <http://dbpedia.org/ontology/wikiPageID> "706"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Demographics_of_Angola> <http://dbpedia.org/ontology/wikiPageID> "704"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Politics_of_Angola> <http://dbpedia.org/ontology/wikiPageID> "705"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Asia_Minor_(disambiguation)> <http://dbpedia.org/ontology/wikiPageID> "694"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Asia> <http://dbpedia.org/ontology/wikiPageID> "689"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Agriculture> <http://dbpedia.org/ontology/wikiPageID> "627"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Anatomy> <http://dbpedia.org/ontology/wikiPageID> "674"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Astronomy_and_Astrophysics/History> <http://dbpedia.org/ontology/wikiPageID> "731"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Foreign_relations_of_Angola> <http://dbpedia.org/ontology/wikiPageID> "710"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Angolan_Armed_Forces> <http://dbpedia.org/ontology/wikiPageID> "709"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Albert_Sidney_Johnston> <http://dbpedia.org/ontology/wikiPageID> "711"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alberta> <http://dbpedia.org/ontology/wikiPageID> "717"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Antigua_And_Barbuda> <http://dbpedia.org/ontology/wikiPageID> "743"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Albania/History> <http://dbpedia.org/ontology/wikiPageID> "755"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Albania/Transnational_Issues> <http://dbpedia.org/ontology/wikiPageID> "758"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Agnostida> <http://dbpedia.org/ontology/wikiPageID> "764"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Allah> <http://dbpedia.org/ontology/wikiPageID> "740"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aikido> <http://dbpedia.org/ontology/wikiPageID> "751"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Afghanistan> <http://dbpedia.org/ontology/wikiPageID> "737"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AOLamer> <http://dbpedia.org/ontology/wikiPageID> "768"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Atlas_(disambiguation)> <http://dbpedia.org/ontology/wikiPageID> "780"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Annual_plant> <http://dbpedia.org/ontology/wikiPageID> "777"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Albania> <http://dbpedia.org/ontology/wikiPageID> "738"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/American_Revolutionary_War> <http://dbpedia.org/ontology/wikiPageID> "771"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Allocution> <http://dbpedia.org/ontology/wikiPageID> "794"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Affidavit> <http://dbpedia.org/ontology/wikiPageID> "795"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Apiales> <http://dbpedia.org/ontology/wikiPageID> "788"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Azerbaijan> <http://dbpedia.org/ontology/wikiPageID> "746"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aries_(constellation)> <http://dbpedia.org/ontology/wikiPageID> "798"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AlbaniaCommunications> <http://dbpedia.org/ontology/wikiPageID> "807"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Afghanistan/Geography> <http://dbpedia.org/ontology/wikiPageID> "814"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Afghanistan/People> <http://dbpedia.org/ontology/wikiPageID> "816"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Asteroid> <http://dbpedia.org/ontology/wikiPageID> "791"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Afghanistan/Military> <http://dbpedia.org/ontology/wikiPageID> "820"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Afghanistan_(1911_Encyclopedia)> <http://dbpedia.org/ontology/wikiPageID> "822"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Anaconda> <http://dbpedia.org/ontology/wikiPageID> "809"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aegean_Sea> <http://dbpedia.org/ontology/wikiPageID> "842"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/American_Film_Institute> <http://dbpedia.org/ontology/wikiPageID> "869"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AU> <http://dbpedia.org/ontology/wikiPageID> "858"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aircraft> <http://dbpedia.org/ontology/wikiPageID> "849"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Austria/Transnational_issues> <http://dbpedia.org/ontology/wikiPageID> "832"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alfred_Hitchcock> <http://dbpedia.org/ontology/wikiPageID> "808"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Asparagales> <http://dbpedia.org/ontology/wikiPageID> "786"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Arabic> <http://dbpedia.org/ontology/wikiPageID> "803"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Altaic_languages> <http://dbpedia.org/ontology/wikiPageID> "824"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aquarius_(constellation)> <http://dbpedia.org/ontology/wikiPageID> "799"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Aberdeenshire> <http://dbpedia.org/ontology/wikiPageID> "857"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alp_Arslan> <http://dbpedia.org/ontology/wikiPageID> "868"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Anatolia> <http://dbpedia.org/ontology/wikiPageID> "854"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Akira_Kurosawa> <http://dbpedia.org/ontology/wikiPageID> "872"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Analog_Brothers> <http://dbpedia.org/ontology/wikiPageID> "875"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Altenberg> <http://dbpedia.org/ontology/wikiPageID> "885"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Allegiance> <http://dbpedia.org/ontology/wikiPageID> "881"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Abugida> <http://dbpedia.org/ontology/wikiPageID> "878"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Arable_land> <http://dbpedia.org/ontology/wikiPageID> "903"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/AgoraNomic> <http://dbpedia.org/ontology/wikiPageID> "908"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Agnosticism> <http://dbpedia.org/ontology/wikiPageID> "894"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Antimony> <http://dbpedia.org/ontology/wikiPageID> "898"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/ABBA> <http://dbpedia.org/ontology/wikiPageID> "880"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Amsterdam> <http://dbpedia.org/ontology/wikiPageID> "844"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alexander_Graham_Bell> <http://dbpedia.org/ontology/wikiPageID> "852"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Motor_neuron_disease> <http://dbpedia.org/ontology/wikiPageID> "876"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Alfons_Maria_Jakob> <http://dbpedia.org/ontology/wikiPageID> "892"^^<http://www.w3.org/2001/XMLSchema#integer> .

<http://dbpedia.org/resource/Actinium> <http://dbpedia.org/ontology/wikiPageID> "899"^^<http://www.w3.org/2001/XMLSchema#integer> .


In [3]:
import re

In [45]:
int(re.search(r'"\d{1,7}"', line).group()[1:-1])

3509

In [13]:
mapping = []
with open("./page_ids_en.ttl/page_ids_en.ttl") as file:
    lines = file.readlines()
    for line in lines[1:-1]:
        mapping.append({
                "id": line.split(" ")[0],
                "page_id": int(re.search(r'"\d{1,8}"', line).group()[1:-1])
            })

In [10]:
line.split(" ")[0]

'<http://dbpedia.org/resource/Amelia_Ong>'

In [14]:
import pandas as pd
pd.DataFrame(mapping).to_parquet('mapping_dbpedia_wikidata.parquet')